_IMAGENET_CATEGORIES = [
    "kit fox, Vulpes macrotis",
    "English setter",
    "Siberian husky",
    "Australian terrier",
    "English springer, English springer spaniel",
    "grey whale, gray whale, devilfish, Eschrichtius gibbosus, Eschrichtius robustus",
    "lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens",
    "Egyptian cat",
    "ibex, Capra ibex",
    "Persian cat",
    "cougar, puma, catamount, mountain lion, painter, panther, Felis concolor",
    "gazelle",
    "porcupine, hedgehog",
    "sea lion",
    "malamute, malemute, Alaskan malamute",
    "badger",
    "Great Dane",
    "Walker hound, Walker foxhound",
    "Welsh springer spaniel",
    "whippet",
    "Scottish deerhound, deerhound",
    "killer whale, killer, orca, grampus, sea wolf, Orcinus orca",
    "mink",
    "African elephant, Loxodonta africana",
    "Weimaraner",
    "soft-coated wheaten terrier",
    "Dandie Dinmont, Dandie Dinmont terrier",
    "red wolf, maned wolf, Canis rufus, Canis niger",
    "Old English sheepdog, bobtail",
    "jaguar, panther, Panthera onca, Felis onca",
    "otterhound, otter hound",
    "bloodhound, sleuthhound",
    "Airedale, Airedale terrier",
    "hyena, hyaena",
    "meerkat, mierkat",
    "giant schnauzer",
    "titi, titi monkey",
    "three-toed sloth, ai, Bradypus tridactylus",
    "sorrel",
    "black-footed ferret, ferret, Mustela nigripes",
    "dalmatian, coach dog, carriage dog",
    "black-and-tan coonhound",
    "papillon",
    "skunk, polecat, wood pussy",
    "Staffordshire bullterrier, Staffordshire bull terrier",
    "Mexican hairless",
    "Bouvier des Flandres, Bouviers des Flandres",
    "weasel",
    "miniature poodle",
    "Cardigan, Cardigan Welsh corgi",
    "malinois",
    "bighorn, bighorn sheep, cimarron, Rocky Mountain bighorn, Rocky Mountain sheep, Ovis canadensis",
    "fox squirrel, eastern fox squirrel, Sciurus niger",
    "colobus, colobus monkey",
    "tiger cat",
    "Lhasa, Lhasa apso",
    "impala, Aepyceros melampus",
    "coyote, prairie wolf, brush wolf, Canis latrans",
    "Yorkshire terrier",
    "Newfoundland, Newfoundland dog",
    "brown bear, bruin, Ursus arctos",
    "red fox, Vulpes vulpes",
    "Norwegian elkhound, elkhound",
    "Rottweiler",
    "hartebeest",
    "Saluki, gazelle hound",
    "grey fox, gray fox, Urocyon cinereoargenteus",
    "schipperke",
    "Pekinese, Pekingese, Peke",
    "Brabancon griffon",
    "West Highland white terrier",
    "Sealyham terrier, Sealyham",
    "guenon, guenon monkey",
    "mongoose",
    "indri, indris, Indri indri, Indri brevicaudatus",
    "tiger, Panthera tigris",
    "Irish wolfhound",
    "wild boar, boar, Sus scrofa",
    "EntleBucher",
    "zebra",
    "ram, tup",
    "French bulldog",
    "orangutan, orang, orangutang, Pongo pygmaeus",
    "basenji",
    "leopard, Panthera pardus",
    "Bernese mountain dog",
    "Maltese dog, Maltese terrier, Maltese",
    "Norfolk terrier",
    "toy terrier",
    "vizsla, Hungarian pointer",
    "cairn, cairn terrier",
    "squirrel monkey, Saimiri sciureus",
    "groenendael",
    "clumber, clumber spaniel",
    "Siamese cat, Siamese",
    "chimpanzee, chimp, Pan troglodytes",
    "komondor",
    "Afghan hound, Afghan",
    "Japanese spaniel",
    "proboscis monkey, Nasalis larvatus",
]
